### ISSUE TITLE
Allow for hostnames in config files.

### ISSUE THREAD

**Issue by KosherBacon** [NAVCoin/navtech#47]
Presently everything is configured via IPs. I'd like to be able to use hostnames instead. I'm working on setting this up as a Docker swarm stack (because I want to automate the deployment process as much as possible). I'm nearly done. However, because Docker doesn't support static IPs on overlay networks, I can't necessarily know the IP a priori for each service.

However Docker networks will allow containers to talk to each other via hostname. Thus it'd be beneficial to do something like the following:

```
services:
  navtech_incoming:
    build: ./navtech
    depends_on:
      - core_incoming
    ports:
      - "3000:3000"
    networks:
      - primary
  core_incoming:
    build: ./navcoin
    ports:
      - "44444:44444"
    networks:
      - primary
...
```

```
...
"navCoin": {
  "user": "RPC_USERNAME",
  "pass": "RPC_PASSWORD",
  "host": "core_incoming",
  "port": "44444",
  "walletPassphrase": "NAVCOIN_WALLET_PASSPHRASE"
},
...
```

For the time being, I've setup my docker-compose.yml file to use a macvlan and get an IP address from the router, but that's far from optimal.
